use new_schema;
                                          -- PART A--
#1.Find the total quantity sold from all sales records
select sum(quantity) as Total_quantity from sale_data;

#2.Show the total quantity sold for each product. 
select p.product,sum(s.quantity) as Total_quantity 
from sale_data s join product_data p 
on s.product_id = p.id
group by p.product;

#3.Calculate the total revenue generated for each product.
select p.product,sum(s.quantity * p.price) as Total_revenue
from product_data p join sale_data s 
on s.product_id = p.id
group by p.product;

#4.Display the total number of orders placed by each customer.
SELECT c.name, COUNT(s.id) AS Total_orders
FROM sale_data s
JOIN customer_data c ON s.customer_id = c.id
GROUP BY c.name;

#5.Show total sales quantity for each city.
select l.city, sum(s.quantity) as tota_sales_quantity
from location_data l join sale_data s
on l.id = s.location_id
group by l.city;

#6.Find the top 5 best-selling products based on quantity sold.
select p.product,sum(s.quantity) as total_quantity 
from product_data p join sale_data s
on s.product_id = p.id
group by p.product
order by total_quantity desc limit 5;

#7.Calculate the total revenue generated by each employee.
select e.name,sum(s.quantity * p.price) as Total_revenue
from employee_data e join sale_data s 
on s.employee_id = e.id
join product_data p on s.product_id = p.id
group by e.name;
---------------------------------------------------------------------------------------
                              -- PART 2 --
               -- EASY LEVEL (Basics, Aggregation, Simple Joins)--
#1.Find the total quantity sold across all sales.
select sum(quantity) as Total_quantity from sale_data;

#2.Display total sales quantity for each product.
select p.product,sum(s.quantity) as total_quantity from sale_data s join product_data p
on s.product_id = p.id
group by product;

#3. Show total revenue generated from all sales. 
select sum(s.quantity * p.price) as Total_revenue
from sale_data s join product_data p
on s.product_id = p.id;

#4.Find the total number of orders placed by each customer.
SELECT c.name, COUNT(s.id) AS Total_orders
FROM sale_data s
JOIN customer_data c ON s.customer_id = c.id
GROUP BY c.name;

#5. List total sales amount for each city.
select l.city, sum(s.quantity * p.price) as tota_sales_amount from location_data l join product_data p
on l.id = p.id 
join sale_data s on p.id = s.product_id
group by l.city;

#4.Find the number of products sold in each state. 
select l.state,count(s.id) as no_product 
from location_data l join sale_data s
on l.id = s.location_id
group by state;

#7.Display average quantity sold per transaction. 
select avg(quantity) as average_quantity from sale_data;

---------------------------------------------------------------------------

#8.Count how many sales each employee has made. 
select employee_id,count(id) as no_sales from sale_data group by employee_id;

select  e.name,s.employee_id,count(s.id) as sales from sale_data s join employee_data e 
on s.employee_id = e.id
group by e.name,s.employee_id;
----------------------------------------------------------------------------

#9.Find the minimum and maximum product price. 
select min(price)  as minimum_price, max(price)  as maximum_price from product_data;
---------------------------------------------------------------------------------------

#10.Show total tax collected from all sales.
SELECT SUM(s.quantity * p.price * p.`tax rate`) AS total_tax
FROM sale_data s
JOIN product_data p ON s.product_id = p.id;

SELECT s.id,sum(p.`tax rate`) as total_tax from sale_data s join product_data p
on s.product_id = p.id
group by s.id;

----------------------------------------------------------------------------------------
                                -- PART 3 --
# 1. Identify customers who have spent more than the average customer spending.
select c.name,sum(s.quantity * p.price) as total_spending
 from sale_data s join product_data p
on s.product_id = p.id
join customer_data c on s.customer_id = c.id
group by c.id, c.name
having total_spending >(
select avg(cus_spending)
from(
select sum(s.quantity * p.price) as cus_spending
from sale_data s join product_data p
on s.product_id = p.id
group by s.customer_id) as temp);

# 2.Show the monthly sales trend (year-wise and month-wise). 
select month(date) as month_wise , year(date) as year_wise, sum(s.quantity * p.price) as Total_revenue
from sale_data s join product_data p
on s.product_id = p.id
group by month(date) , year(date);

# 3.Find the most profitable product.
select product,sum(s.quantity * p.price * p.`profit margine`) as total_profit,
max(sum(s.quantity * p.price * p.`profit margine`)) Over ( ) as maximum
from product_data p join sale_data s 
on s.product_id = p.id
group by product
order by sum(s.quantity * p.price * p.`profit margine`) DESC LIMIT 1 ;

SELECT 
    p.product,
    SUM(s.quantity * p.price * p.`profit margine`) AS total_profit
FROM product_data p
JOIN sale_data s 
    ON s.product_id = p.id
GROUP BY p.product
ORDER BY total_profit DESC
LIMIT 1;

#4.Rank all products based on their total revenue. 
select p.product , sum(s.quantity * p.price) as total_revenue,
rank( ) over (order by sum(s.quantity * p.price) desc) as rnk
from  product_data p join sale_data s
on s.product_id = p.id
group by p.product;

#5. Find the top-spending customer in each city.
select * from  (
select l.city,c.name,sum(s.quantity * p.price) as total_spending,
RANK() OVER (PARTITION BY l.city ORDER BY SUM(s.quantity * p.price) DESC) AS rnk
from  product_data p join sale_data s
on s.product_id = p.id
join customer_data c on  s.customer_id = c.id
join location_data l on s.location_id = l.id
group by c.name,l.city ) as t  where rnk = 1;



#.6 Calculate the running total of daily sales.
select date(s.date) as date, month(s.date) as month , sum(s.quantity * p.price) as total_sales,
sum(sum(s.quantity * p.price)) OVER (Order by date(s.date)) as running_total
from product_data p join sale_data s 
on s.product_id = p.id
group by Month(s.date) ,date(s.date) ;

#.7 Generate an employee performance report using total revenue. 
select e.name, sum(s.quantity * p.price) as total_revenue
from employee_data e join sale_data s 
on s.employee_id = e.id
join product_data p on s.product_id = p.id
group by e.name
ORDER BY total_revenue DESC;

#.8. Find products whose total profit is above the average profit.
select product,sum(s.quantity * p.price * p.`profit margine`) as total_profit
from product_data p join sale_data s 
on s.product_id = p.id
group by product 
Having total_profit > (
select avg(total_profit)
from (
select sum(s.quantity * p.price * p.`profit margine`) as total_profit
from product_data p join sale_data s 
on s.product_id = p.id
group by product)  as temp);

#9.Rank customers based on their total number of purchases
select c.name,count(s.id) as total_purchases,
rank() OVER (order by count(s.id) desc) as rnk
FROM sale_data s
JOIN customer_data c ON s.customer_id = c.id
GROUP BY c.name;

#10.---
SELECT p.product,SUM(s.quantity * p.price) AS product_revenue,
    ROUND( SUM(s.quantity * p.price) * 100.0 / 
        (SELECT SUM(s.quantity * p.price)
         FROM sale_data s
         JOIN product_data p ON s.product_id = p.id),2
    ) AS revenue_percentage
FROM product_data p
JOIN sale_data s ON s.product_id = p.id
GROUP BY p.product;

-----------------------------------------------------------------------------------------------
                                         -- PART 4 --
                       -- INTERMEDIATE LEVEL (Joins, GROUP BY, Subqueries) --
#11. Find the top 5 products by total quantity sold. 
select p.product,sum(s.quantity) as total_quantity from product_data p join sale_data s
on s.product_id = p.id
group by p.product
order by total_quantity desc limit 5;

#12. Display total revenue generated by each employee. 
select e.name, sum(s.quantity * p.price) as total_revenue from employee_data e join sale_data s
on s.employee_id = e.id
join product_data p on s.product_id = p.id
group by e.name;

#13. Show total spending by each customer.
select c.name, sum(s.quantity * p.price) as total_spending from customer_data c join sale_data s
on s.customer_id = c.id
join product_data p on s.product_id = p.id
group by c.name;

#14. Find customers whose total spending is above the average spending.
select c.name, sum(s.quantity * p.price) as total_spending from customer_data c join sale_data s
on s.customer_id = c.id
join product_data p on s.product_id = p.id
group by c.name
having sum(s.quantity * p.price) > (
select avg(total_spending) from (
select sum(s.quantity * p.price) as total_spending from  sale_data s 
join product_data p on s.product_id = p.id
group by  s.customer_id
) as h ) ;

#15. Display monthly sales trend (year-wise and month-wise).
select year(s.date) as year, month(s.date) as month, sum(s.quantity * p.price) as total_revenue from sale_data s join product_data p
on s.product_id = p.id
group by year,date
order by year,date;
 
 #16. Find the most profitable product.
 select p.product,sum(s.quantity * p.`profit margine`) as total_profit from product_data p join sale_data s
on s.product_id = p.id
group by p.product
order by total_profit desc limit 1;

#17. Show revenue generated in each country.
select l.countries,avg(s.quantity * p.price) as total_revenue from location_data l join sale_data s
on s.location_id = l.id
join product_data p on p.id = s.product_id
group by l.countries;

#18.18. List customers who have made more than 5 purchases.
select c.name,count(s.id) as purchase from customer_data c join sale_data s 
on  s.customer_id = c.id
group by c.name
having count(s.id) > 5;

#19. Find products that were never sold.
select p.product from product_data p left join sale_data s ON s.product_id = p.id
where s.product_id IS NULL;

# 20.Display average revenue per transaction for each city.
select l.city,avg(s.quantity * p.price) as average_revenue from location_data l join sale_data s
on s.location_id = l.id
join product_data p on p.id = s.product_id
group by l.city;

#21. Find employees who have not made any sales. 
select e.name from employee_data e left join sale_data s ON s.employee_id = e.id
where s.employee_id IS NULL;

#23. Find the city with the highest total revenue. 
select l.city,sum(s.quantity * p.price) as hig_tot_revenue from location_data l join sale_data s
on s.location_id = l.id
join product_data p on p.id = s.product_id
group by l.city
order by  hig_tot_revenue desc limit 1;
--------------------------------------------------------------------------
#24. Display product-wise profit margin contribution.
select product,`profit margine` from product_data;

SELECT p.product, SUM(s.quantity * p.`profit margine`) AS total_profit
FROM sale_data s
JOIN product_data p ON s.product_id = p.id
GROUP BY p.product;

----------------------------------------------------------------------------
#25. Find the customer who placed the highest number of orders. 
select c.name,count(s.id) as no_of_order from customer_data c join sale_data s 
on  s.customer_id = c.id
group by c.name
order by no_of_order desc limit 1;

---- (USING SUBQUERIE)
select c.name,count(s.id) as no_of_order from customer_data c join sale_data s 
on  s.customer_id = c.id
group by c.name
having no_of_order = ( 
select max(no_of_order) from (select count(s.id) as no_of_order from sale_data s
group by s.customer_id 
) as h);
----------------------------------------------------------------------------------------
                                        -- PART 5 --
                    -- ADVANCED LEVEL (Window Functions, CTE, Complex Analytics) --
#26.Rank products based on total revenue.				
select p.product,sum(s.quantity*p.price) as total_revenue,
rank() over (order by sum(s.quantity*p.price)  desc) as rank_no
from  product_data p join sale_data s
on s.product_id = p.id
group by p.product;

# 27. Rank customers by total spending. 
select c.name,sum(s.quantity*p.price) as total_spending,
rank() over (order by sum(s.quantity*p.price)  desc) as rank_no
from  customer_data c join sale_data s
on s.customer_id = c.id
join product_data p on s.product_id = p.id
group by c.name;

#28. Find the top customer in each city based on revenue.
select * from(
select l.city, c.name,sum(s.quantity*p.price) as total_spending,
rank() over (partition by l.city order by sum(s.quantity*p.price)  desc) as rank_no
from  customer_data c
join sale_data s on s.customer_id = c.id
join product_data p on s.product_id = p.id
join location_data l on s.location_id = l.id
group by c.name, l.city
) t 
where rank_no = 1;

# 29.Calculate running total of daily sales.
select date(s.date) as sale_date , sum(s.quantity * p.price) as total_sales,
sum(sum(s.quantity * p.price)) Over ( Order by date(s.date)) as running_sales
from product_data p join sale_data s 
on s.product_id = p.id
group by date(s.date);

#30. Find month-over-month sales growth. 
select year,month, total_sales,
total_sales - lag (total_sales) over (order by month,year) as growth
from (
select year(s.date) as year,Month(s.date) as month , sum(s.quantity * p.price) as total_sales
from product_data p join sale_data s 
on s.product_id = p.id
group by Month(s.date),year(s.date)
) AS s;

#31. Identify employees whose performance is above company average.
select e.name,sum(s.quantity*p.price) as performance
from employee_data e join sale_data s 
on s.employee_id = e.id join product_data p
on s.product_id = p.id
group by e.name
having performance > (
select avg(avg_per)
from (
select sum(s.quantity*p.price) as avg_per
from employee_data e join sale_data s 
on s.employee_id = e.id join product_data p
on s.product_id = p.id
group by e.name ) as temp);

#32. Find products whose profit is above average profit.
select p.product,sum(s.quantity * p.price * p.`profit margine`) as total_profit
from product_data p join sale_data s 
on s.product_id = p.id
group by p.product
having sum(s.quantity * p.price * p.`profit margine`) > (
select avg(avg_profit)
from ( 
select sum(s.quantity * p.price * p.`profit margine`) as avg_profit
from product_data p join sale_data s 
on s.product_id = p.id
group by p.product) as t);
#33. Show each product’s percentage contribution to total revenue.
SELECT p.product,SUM(s.quantity * p.price) AS total_revenue,
ROUND(SUM(s.quantity * p.price) * 100.0 /
        (SELECT SUM(s.quantity * p.price)
         FROM sale_data s JOIN product_data p ON s.product_id = p.id),2) AS revenue_percentage
FROM product_data p
JOIN sale_data s ON s.product_id = p.id
GROUP BY p.product;
#34. Find the second highest selling product.
select product,quantity
from(
select p.product,sum(s.quantity) as quantity,
dense_rank () over (order by sum(s.quantity) desc) as revenue
from product_data p join sale_data s 
on s.product_id = p.id
group by p.product
) t
where revenue = 2;

#35. Display top 3 customers in each state.
select *
from(
select c.name , l.state,sum(s.quantity*p.price) as spending,
rank()  over(partition by c.name order by sum(s.quantity*p.price) desc) as revenue
from location_data l join sale_data s 
on s.product_id = l.id join customer_data c
on s.customer_id = c.id join product_data p
on s.product_id = p.id
group by l.state, c.name
) t
where revenue < 4;
 
#36. Identify repeat customers (customers with purchases in multiple months).
WITH monthly AS (
    SELECT customer_id,
           DATE_FORMAT(date, '%Y-%m') AS month
    FROM sale_data
    GROUP BY customer_id, month )
SELECT c.id, c.name
FROM sale_data s
JOIN customer_data c ON s.customer_id = c.id
GROUP BY c.id, c.name
HAVING COUNT(*) > 1;

# 37.Calculate moving average of sales for the last 3 days. 
SELECT DATE(s.date) AS sale_date,SUM(s.quantity * p.price) AS daily_sales,
AVG(SUM(s.quantity * p.price)) OVER (ORDER BY DATE(s.date) ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS 3_days
FROM sale_data s
JOIN product_data p ON s.product_id = p.id
GROUP BY DATE(s.date);

#38. Find customers whose spending is increasing month by month.
WITH monthly AS (
    SELECT c.id,c.name,DATE_FORMAT(s.date, '%Y-%m') AS month,SUM(s.quantity * p.price) AS total_spent FROM sale_data s
    JOIN customer_data c ON s.customer_id = c.id
    JOIN product_data p ON s.product_id = p.id
    GROUP BY c.id, c.name, month
)
SELECT *
FROM (
    SELECT *,
           LAG(total_spent) OVER (PARTITION BY id ORDER BY month) AS prev_spent
    FROM monthly) t
WHERE total_spent > prev_spent;
 
#39. Classify employees as High / Medium / Low performers using revenue.
select e.name,sum(s.quantity*p.price) as total_revenue,
case
when sum(s.quantity*p.price) > 1000 then "HIGH_PERFORMANCE" 
when sum(s.quantity*p.price) > 500 then  "MID_PERFORMANCE"
when sum(s.quantity*p.price) > 1 then  "LOW_PERFORMANCE"
END as PERFORMANCE ,
rank() OVER(Order by sum(s.quantity * p.price) ) as revenue  from employee_data e
join sale_data s on s.employee_id = e.id
join product_data p on s.product_id = p.id
group by e.name;

#40. Find cities where sales declined compared to previous month.
with monthly as(
select l.city,DATE_FORMAT(s.date, '%Y-%m')as month,sum(s.quantity * p.price)  as total_sales
from location_data l join sale_data s on s.location_id = l.id
join product_data p on s.product_id  = p.id
group by l.city,month
)
select * from ( 
select * ,
 lag(total_sales) over(partition by city order by month) as prev_month
 from monthly ) as t
 where total_sales >  prev_month;

#41.Identify the most consistent selling product (least variation).
with daily_sale As  (
  select p.product,sum(s.quantity * p.price) as total_sales,date(s.date) as sale_date
  from sale_data s join product_data p  on
  s.product_id = p.id
  group by p.product,sale_date
  )
  SELECT 
    product,
    STDDEV(total_sales) AS variation
FROM daily_sale
GROUP BY product
ORDER BY variation ASC
LIMIT 1;
  
  


#42. Find customers who have purchased from more than 3 cities.
select * from (
select c.name,l.city, count(s.id) as purchase,
rank()  over(partition by c.name order by count(s.id) desc) as rn
from location_data l join sale_data s 
on s.location_id = l.id join customer_data c
on s.customer_id = c.id
group by l.city, c.name
) as d
where purchase > 3;

#43. Find the first and last purchase date for each customer.
select c.name, date(s.date) as p_date ,    
MIN(DATE(s.date)) OVER (PARTITION BY c.name) AS first_purchase,
MAX(DATE(s.date)) OVER (PARTITION BY c.name) AS last_purchase
from customer_data c join sale_data s 
on s.customer_id = c.id;

#44. Detect peak sales days using ranking functions.
select date(s.date) as sale_date, sum(s.quantity * p.price) as total_sales,
rank()  over(order by sum(s.quantity * p.price)  desc) as rnk 
from product_data p join sale_data s 
on s.product_id = p.id
group by sale_date; 

# 45.Find products that dominate more than 30% of revenue in any city.
with city_sales as (
select p.product,sum(s.quantity*p.price) as revenue,l.city,
SUM(SUM(s.quantity * p.price)) OVER (PARTITION BY l.city) AS total_city
from product_data p JOIN sale_data s
on p.id = s.product_id join location_data l on s.location_id = l.id 
group by l.city,p.product
) 
select * from city_sales
where revenue/total_city > 0.3;


#46.Generate a customer lifetime value report.
select c.name , sum(s.quantity * p.price) as customer_lifetime
from customer_data c join sale_data s 
on s.customer_id = c.id
join product_data p on s.product_id = p.id
group by c.name
order by customer_lifetime desc ;

# 47. Compare weekday vs weekend sales performance. 
with sales_performance As(
select date(s.date) as date,sum(s.quantity * p.price) as revenue,
CASE
   When dayofweek(s.date) IN (1,7) THEN 'Weekend'
   Else 'weekday'
   End  as day_type
from sale_data s join product_data p on s.product_id = p.id
group by date(s.date),day_type)
select day_type,
    avg(revenue) as avg_rev,
    max(revenue) as max_rev,
    min(revenue) as min_rev
    from sales_performance
    group by day_type;

#48. Find employees whose sales rank improved over time. 
WITH emp_month AS (
    SELECT 
        e.id,
        e.name,
        DATE_FORMAT(s.date, '%Y-%m') AS month,
        SUM(s.quantity * p.price) AS total_sales
    FROM sale_data s
    JOIN employee_data e ON s.employee_id = e.id
    JOIN product_data p ON s.product_id = p.id
    GROUP BY e.id, e.name, month
),
ranked AS (
    SELECT *,
           RANK() OVER (PARTITION BY month ORDER BY total_sales DESC) AS rnk
    FROM emp_month
)
SELECT *
FROM (
    SELECT *,
           LAG(rnk) OVER (PARTITION BY id ORDER BY month) AS prev_rank
    FROM ranked
) t
WHERE rnk < prev_rank;

# 49. Create a sales funnel report using CTE. 
WITH visitors AS (
    SELECT COUNT(DISTINCT customer_id) AS total_visitors
    FROM sale_data
),
buyers AS (
    SELECT COUNT(DISTINCT customer_id) AS total_buyers
    FROM sale_data
    WHERE quantity > 0
),
repeat_customers AS (
    SELECT COUNT(*) AS repeat_count
    FROM (
        SELECT customer_id
        FROM sale_data
        GROUP BY customer_id
        HAVING COUNT(*) > 1
    ) t
),
high_value_customers AS (
    SELECT COUNT(*) AS high_value
    FROM (
        SELECT s.customer_id,
               SUM(s.quantity * p.price) AS total_spent
        FROM sale_data s
        JOIN product_data p ON s.product_id = p.id
        GROUP BY s.customer_id
        HAVING SUM(s.quantity * p.price) > 10000
    ) t
)
SELECT 
    v.total_visitors,
    b.total_buyers,
    r.repeat_count,
    h.high_value
FROM visitors v, buyers b, repeat_customers r, high_value_customers h;

# 50. Build a consolidated sales summary using multiple CTEs.
WITH daily AS (
    SELECT 
        DATE(s.date) AS period,
        'Daily' AS level,
        SUM(s.quantity * p.price) AS revenue
    FROM sale_data s
    JOIN product_data p ON s.product_id = p.id
    GROUP BY DATE(s.date)
),
monthly AS (
    SELECT 
        DATE_FORMAT(s.date, '%Y-%m') AS period,
        'Monthly' AS level,
        SUM(s.quantity * p.price) AS revenue
    FROM sale_data s
    JOIN product_data p ON s.product_id = p.id
    GROUP BY DATE_FORMAT(s.date, '%Y-%m')
),
yearly AS (
    SELECT 
        YEAR(s.date) AS period,
        'Yearly' AS level,
        SUM(s.quantity * p.price) AS revenue
    FROM sale_data s
    JOIN product_data p ON s.product_id = p.id
    GROUP BY YEAR(s.date)
),
overall AS (
    SELECT 
        'All Time' AS period,
        'Overall' AS level,
        SUM(s.quantity * p.price) AS revenue
    FROM sale_data s
    JOIN product_data p ON s.product_id = p.id
)
SELECT * FROM daily
UNION ALL
SELECT * FROM monthly
UNION ALL
SELECT * FROM yearly
UNION ALL
SELECT * FROM overall;



